FROM gcc:13.2 AS builder

WORKDIR /build

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/catseye/Befunge-93.git && \
    cd Befunge-93 && \
    gcc -o befunge src/bef.c

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /build/Befunge-93/befunge /usr/local/bin/befunge

COPY app/main.bf .

CMD ["befunge", "main.bf"]
