FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY app/pom.xml app/pom.xml

RUN cd app && mvn dependency:go-offline -B

COPY app app

RUN cd app && mvn package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/app/target/app.jar .

CMD ["java", "-jar", "app.jar"]
