FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY app/pom.xml ./app/

RUN mvn -f ./app/pom.xml dependency:go-offline -B

COPY app ./app

RUN mvn -f ./app/pom.xml package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/target/app.jar .

CMD ["java", "-jar", "app.jar"]
